### PR TITLE
Fix slashing

### LINKED ISSUE #663: Fix Slashing in Thea-Staking Pallet
**Current implementation For Slashing**

current_slash

**New Implementation For Slashing**

The reserve balance should not be the primary source for slash amounts. Instead, it should be considered as the last resort. The initial basis for the slash amount should be taken from the free balance. Only if necessary, the reserve balance should be utilized for the slash amount.

Update the storage values of nominators and relayers.

slash excalidraw (3) (1)

### PR DESCRIPTION
**Pull request by nakul1010**
Pr Fixes #663.

### CODE REVIEW

File: pallets/thea-staking/src/lib.rs [hunk 1]
```diff
@@ -520,6 +524,8 @@ pub mod pallet {
 		RepeatedReport,
 		/// Not a member of active relayers
 		NotAnActiveRelayer,
+		/// Amount to stash is greater than bonded amount
+		AmountToStashGreaterThanBondedAmount,
```
Comment (serhii-temchenko) [inline pallets/thea-staking/src/lib.rs]: I assume typo in `Stash` in comment and in enum variant

**Review by serhii-temchenko — CHANGES_REQUESTED** [review]

File: pallets/thea-staking/src/lib.rs (hunk 1 above)
Comment (nakul1010) [reply pallets/thea-staking/src/lib.rs]: Done

**Review by serhii-temchenko — APPROVED** [review]

**Review by 35359595 — APPROVED** [review]
LGTM
